### ISSUE TITLE
Implement bookmarks

### ISSUE THREAD

**Issue by icedream** [icedream/icecon#1]
Currently users can use existing ways in their operating systems (like Windows shortcuts or Linux shell scripts) in order to quickly run IceCon with the right connection details (`icecon [-gui] <server:port> <password>`).

However to make access even easier for most people we can add a bookmark menu entry and save all bookmarks in a secondary file, either in the folder where the tool is running or in the user's home/application data folder.

**Comment by TheIndra55** [comment]
I'd love to implement this by a pull request sometime

**Comment by icedream** [comment]
Reopening as there is a pending review/reimplementation.
