### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by daviddusty** [icedream/icecon#14]

**Comment by icedream** [comment]
Which Linux distribution are you running? Also did you make sure to run `chmod +x icecon` to make the files you downloaded executable at all? Does `./icecon` (instead of without ./) also not work?

**Comment by mamadlooloo** [comment]
I'm using CentOS 7.
Yes it's working YES ...
Thanks ...
--------------------------------------
First:
chmod +x icecon_linux_i386
Second:
./icecon_linux_i386 --command="restart policejob" 127.0.0.1:30120 passwordhere
--------------------------------------
Working ...

**Comment by icedream** [comment]
Awesome! :) If you are on 64-bit, make sure to use the amd64 variant, the i386 variant is for 32-bit computers. Other than that, feel free to open a new issue if you run into issues.
