### ISSUE TITLE
Status command

### ISSUE THREAD

**Issue by AceGrid** [icedream/icecon#7]
The status command isn't working when i type status in IceCon when im connected it says : 

IPADRESS> status
InvokeNative: execution failed: Argument at index 0 was null.
Error running system event handling function for resource rconlog: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: Execution of native 00000000ff7f66ab in script host failed.
stack traceback:
	[C]: in upvalue '_in'
	citizen:/scripting/lua/natives_server.lua:97: in function 'GetNumPlayerIdentifiers'
	citizen:/scripting/lua/scheduler.lua:245: in function 'GetPlayerIdentifiers'
	rconlog_server.lua:55: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:173>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:173: in function <citizen:/scripting/lua/scheduler.lua:138>
No such command status.

**Comment by AceGrid** [comment]
Pls help me as quickly as possible because i need the console for the server.

**Comment by icedream** [comment]
Unfortunately this error is not related to icecon but to the server software you are using (in this case it seems to be the CitizenFX server). The log actually points you to the places in the Lua scripts in which these errors occur.
