### ISSUE TITLE
icecon rcon tool not working

### ISSUE THREAD

**Issue by JordRichoTV31** [icedream/icecon#9]
**The text box reacts by playing the Windows Ding sound when pressing Enter in it due to it not being able to handle multiline. this needs to be sorted asap**

**Comment by icedream** [comment]
The Windows Ding sound problem is known (#2), nevertheless the application should still accept the command just fine. Does it hinder you from using the application? If yes, can you explain in steps how you ran into the error? Otherwise I'll be closing this issue as duplicate.
